name: release
on:
    push:
        tags:
            - '*'
jobs:
    release:
        name: Publish release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build and publish images
              run: |
                version="$(echo "${{ github.ref }}" | cut -d / -f 3)"
                ./scripts/build -p . "$version"
                echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u matteodelabre --password-stdin
